on:
  workflow_call:
    inputs:
      push_to_images:
        type: string
      version_prerelease:
        type: string
      version_metadata:
        type: string
      flavor:
        type: string
      tags:
        type: string
      labels:
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish_x86:
    concurrency: 
      group: ${{ github.ref }}-x86
      cancel-in-progress: true
    permissions:
      packages: write

    outputs:
      tag: ${{ steps.set_output.outputs.tag }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mirror
        uses: self-actuated/hub-mirror@master
        
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - uses: docker/metadata-action@v4
        id: meta
        if: ${{ inputs.push_to_images != '' }}
        with:
          images: ${{ inputs.push_to_images }}
          flavor: |
            suffix=-amd64
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
      
      - name: Release build
        id: release_build
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            MASTODON_VERSION_PRERELEASE=${{ inputs.version_prerelease }}
            MASTODON_VERSION_METADATA=${{ inputs.version_metadata }}
          platforms: linux/amd64
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name || steps.buildx-native.outputs.name }}
          push: ${{ inputs.push_to_images != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
      - name: Add final tag
        id: set_output
        run: echo "tag=${{ env.DOCKER_METADATA_OUTPUT_TAGS }}">>$GITHUB_OUTPUT

  publish_aarch64:
    concurrency: 
      group: ${{ github.ref }}-aarch64
      cancel-in-progress: true
    permissions:
      packages: write
      
    outputs:
      tag: ${{ steps.set_output.outputs.tag }}
      
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v4

      - name: Setup mirror
        uses: self-actuated/hub-mirror@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - uses: docker/metadata-action@v4
        id: meta
        if: ${{ inputs.push_to_images != '' }}
        with:
          images: ${{ inputs.push_to_images }}
          flavor: |
            suffix=-arm64
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
        
      - name: Release build
        id: release_build
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            MASTODON_VERSION_PRERELEASE=${{ inputs.version_prerelease }}
            MASTODON_VERSION_METADATA=${{ inputs.version_metadata }}
          platforms: linux/arm64
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name || steps.buildx-native.outputs.name }}
          push: ${{ inputs.push_to_images != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Add final tag
        id: set_output
        run: echo "tag=${{ env.DOCKER_METADATA_OUTPUT_TAGS }}">>$GITHUB_OUTPUT

  publish_manifest:
    runs-on: ubuntu-latest
    needs: [publish_x86, publish_aarch64]
    steps:

    - name: Get Repo Owner
      id: get_repo_owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

    - name: Login to container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Consume information
      run: |
        echo "Received data from Job 1: ${{ needs.publish_x86.outputs.tag }}"
        echo "Received data from Job 2: ${{ needs.publish_aarch64.outputs.tag }}"

    - name: Create flavortag
      id: get_flavor_tag
      run: echo "FLAVORTAG=$(echo ${{ needs.publish_aarch64.outputs.tag}} | sed 's/-arm64$//')" >> $GITHUB_ENV

    - name: Create manifest
      run: |
        docker manifest create ${{ env.FLAVORTAG }}\
          --amend ${{ needs.publish_x86.outputs.tag }} \
          --amend ${{ needs.publish_aarch64.outputs.tag }}
        docker manifest annotate --arch amd64 --os linux ${{ env.FLAVORTAG }} ${{ needs.publish_x86.outputs.tag }}
        docker manifest annotate --arch arm64 --os linux ${{ env.FLAVORTAG }} ${{ needs.publish_aarch64.outputs.tag}}
        docker manifest inspect ${{ env.FLAVORTAG }}

        docker manifest push ${{ env.FLAVORTAG }}



