name: Build container release images
on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  compute-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo Owner
        uses: actions/checkout@v4
      - id: get_repo_owner
        run: |
          echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    outputs:
      owner: ${{ steps.get_repo_owner.outputs.REPO_OWNER }}

  build-image:
    uses: ./.github/workflows/build-container-image.yml
    needs: compute-owner
    with:
      push_to_images: |
        emmaae/mastodon-ab
        ghcr.io/${{ needs.compute-owner.outputs.owner }}/bottle
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      flavor: |
        latest=${{ startsWith(github.ref, 'refs/tags/v4.4.') }}
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
    secrets: inherit
