name: Publish Docker image
on:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Determine Branch or Merge Request Name
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            BRANCH_OR_MR_NAME=${GITHUB_REF#refs/heads/}
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            BRANCH_OR_MR_NAME=${GITHUB_HEAD_REF}
          fi
          echo "BRANCH_OR_MR_NAME=${BRANCH_OR_MR_NAME}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_User }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ secrets.DOCKERHUB_User }}/mastodon-ab:${{ env.BRANCH_OR_MR_NAME }}
          build-args: |
            BRANCH=${{ env.BRANCH_OR_MR_NAME }}
